### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by juliuszz** [rfbr/PDR_with_Deep_Learning#4]
Hi，I want to collect data on a new device. How can I get the training data as the example?Is there an APK that can be used directly？
THX!

**Comment by rfbr** [comment]
Hello!
You can use this [repository](https://github.com/rfbr/IMU_and_pose_Android_Recorder) which implements the application we used to collect the data. You will need android studio to build the APK.

**Comment by juliuszz** [comment]
thanks for the project.
